### ISSUE TITLE
C64..archon joysticks?

### ISSUE THREAD

**Issue by Zibri** [floooh/chips-test#11]
Add also archon because it seems to work: http://www.sta.to/64/archon0.prg

Question: how about joysticks?

**Comment by floooh** [comment]
Thanks! Joysticks are currently only emulated through the host system's keyboard and must be activated with an URL- or command-line arg (arrow keys are the direction, space key is fire).

Using gamepads instead of the keyboard emulation is planned, but it will take a while until I get around implementing that.
