### ISSUE TITLE
remove 'image-rendering: pixelated' 

### ISSUE THREAD

**Issue by nippur72** [floooh/chips-test#12]
the `image-rendering: pixelated` in `emsc.html` makes it poor looking in all the main browsers I tried, would you consider dropping it in favor of the default rendering method ? 

To mitigate the softness of the standard rendering, I suggest to double the pixels in the original canvas (both horizontally and vertically) and display the "doubled" version. The result will be very pleasant. I do this in my Laser 500 emulator, see how it looks [here](https://nippur72.github.io/laser500emu/).

(P.S. I'm really amazed by this project, it's totally awesome. I will look into adding VTech Laser 500 and possibly Laser 310 (aka VZ300), but first I have to get acquainted to it and understand how to build properly. For now I keep studying the code, it's so beautifully written).

**Comment by floooh** [comment]
Thanks for the suggestion, but the situation is "complicated" :D

Basically: I'm already doing the scaling-trick you describe:

https://github.com/floooh/chips-test/blob/367775c47b087c7dfc83b7ca9a80db410282589b/examples/common/gfx.h#L252-L286

The original frame buffer is first upscaled 2x with nearest-filtering into an offscreen rendering target, and then rendered to the WebGL canvas with linear filtering, which provides a bit of smoothing.

If the webpage is running on a HighDPI display, there will be another scaling step because the WebGL canvas isn't created as HighDPI and this "browser internal" scaling step is where the canvas CSS settings come in. 

Without having the WebGL canvas pixelated, the text rendering in the debugging UI would look poorly (you can see this effect when running the demos on a Retina Mac in Safari, because Safari doesn't seem to support those pixelated CSS parameters). On Safari, the actual emulator framebuffer looks pretty much the same, but the text rendering in debugging UI looks blurry.

Sooo... it's not as simply as simply deactivation the CSS pixelation unfortunately, but I'll keep the topic in the back of my head :)

**Comment by nippur72** [comment]
I see there is no more pixelation with the [latest commit](https://github.com/floooh/chips-test/commit/1734dd14efcf9e2857b7975689c7ea33a0f84841). Very nice result, I love it!
