### ISSUE TITLE
ay-3-8910 clicky sound?

### ISSUE THREAD

**Issue by nippur72** [floooh/chips-test#14]
I tried `SOUND 1,400,400,15` on the Amstrad CPC 646 emulator, I get a continuous tone but sometimes it's "clicky" -- it has some very noticeable glitch. It's not periodic, it happens randomly every two or two seconds. 

My first thought was a browser buffer issue (AudioContext etc), but then I checked the sound on the VIC-20 emulatore and it's perfectly ok. 

So I guess there's something wrong in the AY-3-8910 emulation? Can you reproduce this issue? 

I'm trying to incorporate `ay38910.h` in an emulator of my own but I'm having problems getting it to work properly, so I was just checking how it works in other emulators before anything else.

**Comment by nippur72** [comment]
update: I checked it several times and I think it's some kind of browser issue (I suspect audioContext latency). The behavior is similar in Chrome, Firefox and Edge. The `ay38910.h` seems ok to me as I redirected the audio to a `.wav` file and it looks fine.

**Comment by floooh** [comment]
Hmm, yeah, running completely glitch free on top of WebAudio is hard, especially when the audio data is coming from the main browser thread using ScriptProcessorNode. One day I need to add a Audio Worklet backend to sokol_audio.h, but it's not sure whether this actually improves anything (because the audio data will still need to be pushed from the main thread).
